### ISSUE TITLE
AttributeError: 'Device' object has no attribute 'unlock'

### ISSUE THREAD

**Issue by klaxonheroku** [jonghwanhyeon/python-switchbot#14]
Hi, 
I'm trying to unlock and lock the SmartLock via commands `lock.lock()` and `lock.unlock()`. Both commands give me an error. I made sure to access the lock by adressing it directly via `devices [0]` and to check it, I'm printing the name of `devices [0]` (to make sure I'm not trying to unlock the HubMini `devices [1]`). Still I get the Error `AttributeError: 'Device' object has no attribute 'unlock'` Please check the terminal ouput and config below.

switchbot_lock.py Terminal Feedback:
```
SmartLock(id=XXXXXXXXX)
HubMini(id= XXXXXXXXX)
{'lock_state': 'locked', 'door_state': 'opened', 'calibrate': True}
SmartLock(id= XXXXXXXXX)
Traceback (most recent call last):
  File "/Users/username/Desktop/switchbot_lock.py", line 42, in <module>
    lock.unlock()
AttributeError: 'Device' object has no attribute 'unlock'

```

switchbot_lock.py Config:
```
# If you already know a device id:
device = switchbot.device(id='XXXXXXXXX')
# Device(id=5F0B798AEF91)

# To query a status of a device
print(device.status())
# {'power': 'off'}

# # To command actions,
# device.command('turn_on')
# device.command('turn_off')
# device.command('press')
# device.command('set_position', parameter='0,ff,80')

# # For some device types like Bot:
# bot = devices[0]
# bot.turn('on')
# bot.turn('off')
# bot.toggle()
# bot.press()

# For some device types like Lock:
lock = devices[0]
print(lock)
lock.unlock()
# lock.unlock()
# lock.toggle()
```

**Comment by fldc** [comment]
I have a lock and I've tried to change Lock.device_type_for to Smart Lock and SmartLock after reading the API docs, both with the same result, am I missing something? :)

**Comment by jonghwanhyeon** [comment]
@fldc, If possible, could you help me solve this issue?

By adding `print(extra)` function to `Device.__init__` in `switchbot/devices.py`,
```python
class Device:
    device_type_for: ClassVar[Optional[str]] = None
    specialized_cls: ClassVar[Dict[str, Device]] = {}

    def __init__(self, client: SwitchBotClient, id: str, **extra):
        self.client = client
        print(extra)
```
Could you please share the output of `extra`?

**Comment by fldc** [comment]
> @fldc, If possible, could you help me solve this issue?
> 
> By adding `print(extra)` function to `Device.__init__` in `switchbot/devices.py`,
> 
> ```python
> class Device:
>     device_type_for: ClassVar[Optional[str]] = None
>     specialized_cls: ClassVar[Dict[str, Device]] = {}
> 
>     def __init__(self, client: SwitchBotClient, id: str, **extra):
>         self.client = client
>         print(extra)
> ```
> 
> Could you please share the output of `extra`?

Absolutely,

Lock.device_type_for is also set to "Smart Lock" when running this.

{'device_id': 'XXXXXXXX', 'device_name': 'Switchbot Hub Mini', 'device_type': 'Hub Mini', 'enable_cloud_service': False, 'hub_device_id': ''}
{'device_id': 'XXXXXXXX', 'device_name': 'Ytterdörr', 'device_type': 'Smart Lock', 'enable_cloud_service': True, 'hub_device_id': 'XXXXXXXX', 'master': True}
HubMini(id=XXXXXXXX)
SmartLock(id=XXXXXXXX)
{}
{'lock_state': 'locked', 'door_state': 'closed', 'calibrate': True}
Traceback (most recent call last):
  File "/opt/docker-data/hass/homeassistant/switchbot_devices.py", line 29, in <module>
    lock.unlock()
AttributeError: 'Device' object has no attribute 'unlock'

**Comment by jonghwanhyeon** [comment]
@fldc First of all, thanks for your help 🤗
I just modified some lines but I cannot test it because I don't have any SwitchBot Lock.
If you could, can you please help me by installing the following version of `python-switchbot`?
```bash
pip install git+https://github.com/jonghwanhyeon/python-switchbot.git@fix-smart-lock
```

Also, it would be very helpful if you can report by running the following code with maksing your device ids:
```python
devices = switchbot.devices()
for device in devices:
    print(device, type(device))
```

**Comment by fldc** [comment]
> @fldc First of all, thanks for your help hugs I just modified some lines but I cannot test it because I don't have any SwitchBot Lock. If you could, can you please help me by installing the following version of `python-switchbot`?
> 
> ```shell
> pip install git+https://github.com/jonghwanhyeon/python-switchbot.git@fix-smart-lock
> ```
> 
> Also, it would be very helpful if you can report by running the following code with maksing your device ids:
> 
> ```python
> devices = switchbot.devices()
> for device in devices:
>     print(device, type(device))
> ```

No problem, so this is the result with the above version,

HubMini(id=XXXX) <class 'switchbot.devices.Device'>
SmartLock(id=XXXX) <class 'switchbot.devices.Lock'>
Traceback (most recent call last):
  File "/opt/docker-data/hass/homeassistant/switchbot_devices.py", line 29, in <module>
    lock.unlock()
AttributeError: 'Device' object has no attribute 'unlock'

**Comment by jonghwanhyeon** [comment]
@fldc Could you tell me how you instantiated the `lock` object? It seems that `lock` is an instance of `Device`, not `Lock`

**Comment by fldc** [comment]
> @fldc Could you tell me how you instantiated the `lock` object? It seems that `lock` is an instance of `Device`, not `Lock`

This is the full test code right now

#!/usr/bin/env python

import uuid
from switchbot import SwitchBot

your_switch_bot_token = 'xxx'
your_switch_bot_secret = 'xxx'
switchbot = SwitchBot(token=your_switch_bot_token, secret=your_switch_bot_secret, nonce=str(uuid.uuid4()))

devices = switchbot.devices()
for device in devices:
    print(device, type(device))

lock = switchbot.device(id='XXX')
lock.unlock()

**Comment by fldc** [comment]
lock.command('unlock') worked though

**Comment by fldc** [comment]
ok, nvm, setting device from array and then lock.unlock() worked fine, how should I define a lock if ID is known? :)

**Comment by jonghwanhyeon** [comment]
@fldc Oh, I got it. I need to query the device information to SwitchBot server when using `device()` method. I'll fix it in a few days. Before that, I think you can use the following workarounds:
```python
lock = switchbot.device(id='XXX', device_type="Smart Lock")
```

**Comment by fldc** [comment]
> 

@jonghwanhyeon That's great, working fine for now atleast, thanks for your help.

**Comment by jonghwanhyeon** [comment]
@fldc  I just fixed this issue. After upgrade the package, you don't need to use `device_type` anymore. Thanks for helping me!
