### ISSUE TITLE
Circular issue

### ISSUE THREAD

**Issue by nasdim** [jonghwanhyeon/python-switchbot#15]
Immediately after running the code, I get the following error: "ImportError: cannot import name 'SwitchBot' from partially initialized module 'switchbot' (most likely due to a circular import)"

**Comment by jonghwanhyeon** [comment]
Could you tell me more detailed information? I would appreciate it if you could tell me how to execute the code.

**Comment by dylanmazurek** [comment]
I'm having this problem with my home assistant.
`Exception in </config/pyscript/apps/switchbot_api/__init__.py> line 3: from switchbot import SwitchBot ^ ImportError: cannot import name 'Device' from 'switchbot.devices' (/usr/local/lib/python3.10/site-packages/switchbot/devices/__init__.py)`

**Comment by nasdim** [comment]
This problem continues in Docker Home Assistant using pyscript @jonghwanhyeon
