### ISSUE TITLE
Update to use the official API (api.switch-bot.com)

### ISSUE THREAD

**Issue by markszabo** [jonghwanhyeon/python-switchbot#7]
@OpenWonderLabs recently released their API documentation: https://github.com/OpenWonderLabs/SwitchBotAPI 

Do you think it would make sense to update this library to use that? 

One difference is authentication: [the API docs recommends](https://github.com/OpenWonderLabs/SwitchBotAPI#getting-started) generating a token, and using that in the `Authorization` header.  This seems like the same token this library generates with cognito though, so it is not necessarily a major change.

**Comment by jonghwanhyeon** [comment]
Close the issue because I updated to use the official API 👍
